http_port 10.50.225.222:3128

acl lab_network src 10.50.225.0/24

acl blocked_domains dstdomain "/etc/squid/blocked_domains.txt"

http_access deny blocked_domains
http_access allow lab_network
http_access deny all